export const getEnvVariables = () => {
    const env = import.meta.env

    return {
        VITE_CURCH_NAME: env.VITE_CURCH_NAME,
        VITE_CURCH_HOUR: env.VITE_CURCH_HOUR,
        VITE_CURCH_LOCATION: env.VITE_CURCH_LOCATION,
        VITE_CURCH_URL_MAPS: env.VITE_CURCH_URL_MAPS,
        VITE_AUDIENCE_NAME: env.VITE_AUDIENCE_NAME,
        VITE_AUDIENCE_HOUR: env.VITE_AUDIENCE_HOUR,
        VITE_AUDIENCE_LOCATION: env.VITE_AUDIENCE_LOCATION,
        VITE_AUDIENCE_URL_MAPS: env.VITE_AUDIENCE_URL_MAPS,
        VITE_RECEPTION_NAME: env.VITE_RECEPTION_NAME,
        VITE_RECEPTION_HOUR: env.VITE_RECEPTION_HOUR,
        VITE_RECEPTION_LOCATION: env.VITE_RECEPTION_LOCATION,
        VITE_RECEPTION_URL_MAPS: env.VITE_RECEPTION_URL_MAPS,
    }
}